services:
  - type: web
    name: claude-code-proxy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: PREFERRED_PROVIDER
        sync: false
      - key: BIG_MODEL
        sync: false
      - key: SMALL_MODEL
        sync: false
